/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _COMMON_H_RPCGEN
#define _COMMON_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


#define RPC_CALCULATOR_PROG ((rpc_uint)0x20000099)
#define RPC_CALCULATOR_VERS ((rpc_uint)1)

#ifdef __cplusplus
#define ADD ((rpc_uint)1)
extern "C" double * add_1(char **, CLIENT *);
extern "C" double * add_1_svc(char **, struct svc_req *);
#define SUBTRACT ((rpc_uint)2)
extern "C" double * subtract_1(char **, CLIENT *);
extern "C" double * subtract_1_svc(char **, struct svc_req *);
#define MULTIPLY ((rpc_uint)3)
extern "C" double * multiply_1(char **, CLIENT *);
extern "C" double * multiply_1_svc(char **, struct svc_req *);
#define DIVIDE ((rpc_uint)4)
extern "C" double * divide_1(char **, CLIENT *);
extern "C" double * divide_1_svc(char **, struct svc_req *);

#elif __STDC__
#define ADD ((rpc_uint)1)
extern  double * add_1(char **, CLIENT *);
extern  double * add_1_svc(char **, struct svc_req *);
#define SUBTRACT ((rpc_uint)2)
extern  double * subtract_1(char **, CLIENT *);
extern  double * subtract_1_svc(char **, struct svc_req *);
#define MULTIPLY ((rpc_uint)3)
extern  double * multiply_1(char **, CLIENT *);
extern  double * multiply_1_svc(char **, struct svc_req *);
#define DIVIDE ((rpc_uint)4)
extern  double * divide_1(char **, CLIENT *);
extern  double * divide_1_svc(char **, struct svc_req *);

#else /* Old Style C */
#define ADD ((rpc_uint)1)
extern  double * add_1();
extern  double * add_1_svc();
#define SUBTRACT ((rpc_uint)2)
extern  double * subtract_1();
extern  double * subtract_1_svc();
#define MULTIPLY ((rpc_uint)3)
extern  double * multiply_1();
extern  double * multiply_1_svc();
#define DIVIDE ((rpc_uint)4)
extern  double * divide_1();
extern  double * divide_1_svc();
#endif /* Old Style C */

#endif /* !_COMMON_H_RPCGEN */
